-- Last updated: 7/17/2026, 3:04:32 PM
WITH BASE AS (
    SELECT
        D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, 
        E.SALARY, 
        DENSE_RANK() OVER 
            (PARTITION BY E.DEPARTMENTID ORDER BY COALESCE(E.SALARY, 0) DESC) AS RK
    FROM DEPARTMENT D JOIN EMPLOYEE E
        ON D.ID=E.DEPARTMENTID
) 
SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM BASE
WHERE RK <=3
ORDER BY DEPARTMENT, SALARY DESC;